routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([ 'as' => 'client.', 'namespace' => 'Client'], function () {
    Route::get('/', 'SiteClentsController@index')->name('index');
    Route::get('/about', 'SiteClentsController@about')->name('about');
    Route::get('/reviews', 'SiteClentsController@reviews')->name('reviews');
    Route::get('/blog', 'SiteClentsController@blog')->name('blog');
    Route::get('/contact', 'SiteClentsController@contact')->name('contact');
    Route::get('new/start', 'SiteClentsController@newstart')->name('new_start');


    Route::resource('registers', 'RegisterLessonController');
    Route::get('lessonRegister', 'RegisterLessonController@store')->name('lessonRegister');
    Route::get('callUp', 'RegisterLessonController@CallUpCenter')->name('CallUpCenter');
    Route::get('SendMSG', 'ContactUsController@Send')->name('sendMSG');


    Route::get('/lesson', 'LessonController@lessons')->name('lesson_danisoft');
    Route::get('/price_list', 'LessonController@price')->name('price_list');
    Route::get('/lesson/{data}', 'LessonController@lessonMore')->name('lessonMore');
    Route::get('/lesson-register/{data?}', 'LessonController@lessonRegister')->name('lessonRegister');
    Route::get('gift-card', 'LessonController@GiftCard')->name('gif_card');
});

Auth::routes();

Route::redirect('/home', '/admin');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/notes', 'HomeController@index')->name('home');
    Route::resource('LessonTimeList', 'School\LessonTimeFolderController');
    Route::post('LessonFolderUpdate', 'School\LessonTimeFolderController@updateStudent')->name('LessonFolderUpdate');
    Route::resource('StudentNewMath', 'School\StudentCreatedNewMath');
    Route::get('StudentNewMath/refresh/Student/{id}', 'School\StudentCreatedNewMath@create')->name('StudentNewMath.new.math');
    Route::get('Student/back/Student/{id}', 'School\StudentCreatedNewMath@showThisStudent')->name('StudentNewMath.showThisStudent');
    Route::resource('StudentList', 'School\StudentCreatedNewMath');
    Route::resource('StudentOfDaniSoft', 'School\StudentController');
    Route::post('LessonTimeList/createNew', 'School\LessonTimeFolderController@addLesson')->name('LessonTimeList.addLesson');
    Route::resource('notes', 'Notes\NotesController');
    Route::post('notes/update/type', 'Notes\NotesController@update')->name('notes.update.type');
    Route::get('notes/fav/type/', 'Notes\NotesController@fav')->name('notes.fav.type');

    //regiser lesson
     Route::resource('registerLesson', 'School\Reg\RegisterLessonController');
     Route::post('registerLessonDelete/{id}', 'School\Reg\RegisterLessonController@delete');
     Route::post('lesson/favorite/type/{id}', 'School\Reg\RegisterLessonController@favorite');
     Route::post('lesson/student/{id}', 'School\Reg\RegisterLessonController@student');
     Route::post('lesson/status/{id}', 'School\Reg\RegisterLessonController@status');
     Route::get('lesson/info/{id}', 'School\Reg\RegisterLessonController@info')->name('lessonReg.info');
     Route::post('lesson/info_store', 'School\Reg\RegisterLessonController@info_store')->name('lessonRegComments.info');


    //endregister

    //CallUp lesson
    Route::resource('CallUp', 'CallUp\CallUpController');
    Route::post('CallUpDelete/{id}', 'CallUp\CallUpController@delete');
    Route::post('CallUp/favorite/type/{id}', 'CallUp\CallUpController@favorite');
    Route::post('CallUp/status/{id}', 'CallUp\CallUpController@status');
    //endCallUp
    //
  //regiser lesson
    Route::resource('contact', 'Contact\ContactUsController');
    Route::post('contactDelete/{id}', 'CallUp\CallUpController@delete');
    Route::post('contact/favorite/type/{id}', 'CallUp\CallUpController@favorite');
    Route::post('contact/status/{id}', 'CallUp\CallUpController@status');
    //endregister



    Route::delete('permissions/destroy', 'User\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'User\PermissionsController');
    Route::delete('roles/destroy', 'User\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'User\RolesController');
    Route::delete('users/destroy', 'User\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'User\UsersController');
});

app/Http/Controllers/Client/LessonController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class LessonController extends Controller
{
    public function lessons(){

        return view('Lesson.lesson');
    }
    public function lessonMore($data_Lesson="frontend"){

        return view('Lesson.show',compact('data_Lesson'));
    }
    public function start(){
        $data_Lesson='new_start';
        return view('Lesson.newLesson',compact('data_Lesson'));
    }
    public function GiftCard(){
        $data_Lesson='new_start';
        return view('Lesson.GiftCard',compact('data_Lesson'));
    }
    public function lessonRegister($data_Lesson_type="web"){

        return view('Lesson.register',compact('data_Lesson_type'));
    }
     public function price(){

        return view('page.priceList');
    }
}

resources/views/Lesson/lesson.blade.php
@extends("layouts.base")
@section('content')
    <div class="breadcrumb-area breadcrumb-bg overlay-black pd-70">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2>Դասընթացներ</h2>
                    <ul>
                        <li><a href="{{route('client.index')}}">Գլխավոր</a></li>
                        <span class="saparator"><i class="fa fa-long-arrow-right"></i></span>
                        <li>Դասընթացներ</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->
    <!-- Courses Area Start -->
    <div class="courses-area pd-top-100">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h2 class="section-title">Frontend դասընթաց</h2>
                </div>
                <div class="col-sm-6">
                    <div class="search-widget">
                        <form action="https://themeunique.com/Studyplus/blog.html" method="post">
                            <input placeholder="Search Your Courses" type="search">
                            <button type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6">
                    <div class="courses-box-item">
                        <div class="course-bg course-bg-1">
                            <i class="like fa fa-heart"></i>
                            <div class="course-title">
                                <h4>ՎԵԲ ԾՐԱԳՐԱՎՈՐՈՒՄԸ 0-ԻՑ</h4>
                                <ul class="course-date">

                                    <li><i class="fa fa-clock-o"></i>6 ամիս</li>
                                </ul>
                            </div>
                            <div class="course-teach-img">
                                <img src="assets/images/lesson/type/basic.png" style="width: 70px;height: 70px;" alt="">

                            </div>
                        </div>
                        <div class="course-desc">
                            <h4>basic course</h4>
                            <p>Պատրա՞ստ ես սկսելու քո ծրագրավորման ուղին, դառնալ պահանջված ծրագրավորող ,ապա մեր դասընթացը հենց քեզ համար է</p>
                            <div class="course-rating">
                                <div class="btnreg">
                                    <div >
                                        <a href="#" class="mybtn-two">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Գրանցվել
                                        </a>
                                    </div>
                                    <div></div>
                                    <div >
                                        <a href="{{route('client.lessonMore','web0')}}" class="mybtn">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Կարդալ Ավելին
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="courses-box-item">
                        <div class="course-bg course-bg-2">
                            <i class="like fa fa-heart"></i>
                            <div class="course-title">
                                <h4>Javascript դասընթաց</h4>
                                <ul class="course-date">

                                    <li><i class="fa fa-clock-o"></i>3 ամիս</li>
                                </ul>
                            </div>
                            <div class="course-teach-img">
                                <img src="assets/images/lesson/type/basic.png" style="width: 70px;height: 70px;" alt="">

                            </div>
                        </div>
                        <div class="course-desc">
                            <h4>basic course</h4>
                            <p>Դասընթացը սկսելու համար ձեզ հարկավոր չէ JavaScript-ի նախնական գիտելիքներ:</p>
                            <div class="course-rating">
                                <div class="btnreg">
                                    <div >
                                        <a href="#" class="mybtn-two">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Գրանցվել
                                        </a>
                                    </div>
                                    <div></div>
                                    <div >
                                        <a href="#" class="mybtn">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Կարդալ Ավելին
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="courses-box-item">
                        <div class="course-bg course-bg-3">
                            <i class="like fa fa-heart"></i>
                            <div class="course-title">
                                <h4>React js դասընթաց</h4>
                                <ul class="course-date">

                                    <li><i class="fa fa-clock-o"></i>2 ամիս</li>
                                </ul>
                            </div>
                            <div class="course-teach-img">
                                <img src="assets/images/lesson/type/basic.png" style="width: 70px;height: 70px;" alt="">
                            </div>
                        </div>
                        <div class="course-desc">
                            <h4>basic course</h4>
                            <p>React js-ը պարզապես սիրված չէ. Այլ ապագա է կարող են մասնակցել այն անձիք ովքերն ունեն Javascript բավարար գիտելիք</p>
                            <div class="course-rating">
                                <div class="btnreg">
                                    <div >
                                        <a href="#" class="mybtn-two">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Գրանցվել
                                        </a>
                                    </div>
                                    <div></div>
                                    <div >
                                        <a href="#" class="mybtn">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Կարդալ Ավելին
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>
    <!-- Courses Area End -->
    <div class="populer-courses  pd">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="section-title">Backend դասընթաց</h2>
                </div>
            </div>
            <div class="row">


                <div class="col-md-4 col-sm-6">
                    <div class="courses-box-item">
                        <div class="course-bg course-bg-4">
                            <i class="like fa fa-heart"></i>
                            <div class="course-title">
                                <h4>PHP դասընթաց</h4>
                                <ul class="course-date">

                                    <li><i class="fa fa-clock-o"></i>3 ամիս</li>
                                </ul>
                            </div>
                            <div class="course-teach-img">
                                <img src="assets/images/lesson/type/basic.png" style="width: 70px;height: 70px;" alt="">

                            </div>
                        </div>
                        <div class="course-desc">
                            <h4>basic course</h4>
                            <p>Բացի այն, որ PHP-ը շատ հեշտ է սովորել։ Դասընթացը սկսելու համար ձեզ հարկավոր չէ PHP-ի նախնական գիտելիքներ:</p>
                            <div class="course-rating">
                                <div class="btnreg">
                                    <div >
                                        <a href="#" class="mybtn-two">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Գրանցվել
                                        </a>
                                    </div>
                                    <div></div>
                                    <div >
                                        <a href="#" class="mybtn">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Կարդալ Ավելին
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>
    <!-- Populer Area Start -->
    <div class="populer-courses  pd">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="section-title">Երեխաների դասընթաց</h2>
                </div>
            </div>
            <div class="row">

                <div class="col-md-4 col-sm-6">
                    <div class="courses-box-item">
                        <div class="course-bg course-bg-5">
                            <i class="like fa fa-heart"></i>
                            <div class="course-title">
                                <h4>«Ապագա Փոքրիկ ծրագրավորող»</h4>
                                <ul class="course-date">

                                    <li><i class="fa fa-clock-o"></i>3 ամիս</li>
                                </ul>
                            </div>
                            <div class="course-teach-img">
                                <img src="assets/images/lesson/type/basic.png" style="width: 70px;height: 70px;" alt="">

                            </div>
                        </div>
                        <div class="course-desc">
                            <h4>basic course</h4>
                            <p>«Ապագա Փոքրիկ ծրագրավորող» դասընթացը՝ 𝟭𝟯-𝟭𝟲տ երեխաների համար</p>
                            <div class="course-rating">
                                <div class="btnreg">
                                    <div >
                                        <a href="#" class="mybtn-two">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Գրանցվել
                                        </a>
                                    </div>
                                    <div></div>
                                    <div >
                                        <a href="#" class="mybtn">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            Կարդալ Ավելին
                                        </a>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <!-- Populer Area End -->

@endsection

resources/views/Lesson/register.blade.php
<html><head>
    <title>Գրանցվել {{$data_Lesson_type}} դասընթացին</title>
     <meta charset="utf-8">
    <meta name="viewport" content="height=device-height,
    width=device-width, initial-scale=1.0,
    minimum-scale=1.0, maximum-scale=1.0,
    user-scalable=no, target-densitydpi=device-dpi">
    <meta name="description" content="Ուսուցման գործընթացը հիմնված է գործնական խնդիրների և ուսուցչի հետ շփման վրա: Մենք միանման դասախոսություններ չունենք: Եվ գիտելիքն անմիջապես գործնականում ամրագրված է:">
    <meta id="dcngeagmmhegagicpcmpinaoklddcgon">
    <link href="{{asset('clent/images/DaniSoft.svg')}}" rel="icon">
    <link href="{{asset('clent/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('clent/css/register.css')}}" type="text/css">

</head>
<body>
<div class="bg-img">
    <div class="content">
        <header>
            <a href="http://danisoft.am">
                <img src="{{asset('clent/images/DaniSoft.png')}}" alt="վիկտորինա դասընթացին" height="150px">
            </a>
            <br>
            <span>Գրանցվել դասընթացներին</span></header>
        <div class="alert alert-success d-none" id="msg_div">
            <span id="res_message">Դուք գրանցվել եք դասընթացին <br>
            մեր մասնագետը կապ կհասատի Ձեզ հետ</span>
        </div>
        <form id="lessonRegister" method="post" action="{{route('client.lessonRegister')}}">
            @csrf
            <div class="field">
                <span class="fa fa-user"></span>
                <span class="text-danger"></span>
                <input type="text" placeholder="Անուն Ազգանուն" name="name" id="formGroupExampleInput">
                <br>
                <br>
            </div>
            <br>
            <div class="field">
                <span class="fa fa-user"></span>
                <span class="text-danger"></span>
                <input type="number" required="" placeholder="Տարիք" name="age">

            </div>
            <br>
            <div class="field">
                <span class="fa fa-user"></span>
                <span class="text-danger"></span>
                <input type="tel" name="tel" placeholder="Հեռախոսահամար">

            </div>
            <br>
            <div class="field">
                <span class="fa fa-user"></span>
                <span class="text-danger"></span>
                <input type="email" placeholder="Փոստ" name="email" id="email">


                <input type="hidden" value="{{$data_Lesson_type}}" name="slug">
            </div>
            <br>

            <div class="pass">
                <br>
            </div>
            <div class="field">
                <input type="submit" value="Հաստատել" id="send_forms_data">
            </div>
        </form>
        <br>
        <div class="signup">Խնդրում ենք հաստատումից առաջ ստուգել Ձեր կողմից լրացված տվյալները

        </div>
    </div>
</div>

<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-129525178-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129525178-1');
</script>

<script src="{{asset('clent/js/jquery/jqueryAjax.min.js')}}"></script>
<script src="{{asset('clent/bootstrap/js/pupoper.js')}}"></script>


<script src="{{asset('clent/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script>

    if ($("#lessonRegister").length > 0) {

        $("#lessonRegister").validate({
            rules: {
            name: {
                required: true,
                    digits: false,
                    maxlength: 50
                },
            tel: {
                required: true,
                    digits: true,
                    minlength: 9,
                    maxlength: 14,
                },

            email: {
                required: true,
                    maxlength: 50,
                    email: true,
                },
            age: {
                required: true,
                    digits: true,
                    minlength: 2,
                    maxlength: 2,
                },
        },
            messages: {
            name: {
                required: "Խնդրում ենք լրացնել Անվանման դաշտը",
                    maxlength: "Շատ երկար է դաշտը"
                },
            tel: {
                required: "Խնդրում ենք լրացնել հեռախոսահամարի դաշտը",
                    digits: "Միայն թիվ",
                    minlength: "Ձեր հեռախոսահամրը չի համապատսխանում",
                    maxlength: "Գրեք ձեր ճիշտ հեռախոսահամրը",
                },

            email: {
                required: "Խնդրում ենք լրացնել փոստը դաշտը",
                email: "Գրեք ձեր փոստը",
                },
            age: {
                required: "Խնդրում ենք լրացնել տարիքի դաշտը",
                    digits: "Միայն թիվ",
                    minlength: "Ձեր տարիքը չի համապատսխանում",
                    maxlength: "Գրեք ձեր ճիշտ տարիքը"
                },
        },
            submitHandler: function (form) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

                    }
                });
                $('#send_forms_data').html('Բեռնում..');
                $.ajax({
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    url: '{{route('client.lessonRegister')}}',
                    type: "get",
                    data: $('#lessonRegister').serialize(),
                    success: function (response) {

                $('#send_form').html('Հաստատված');

                $('#res_message').show();

                $('#res_message').html(response.msg);

                $('#msg_div').removeClass('d-none');


                document.getElementById("lessonRegister").reset();

                setTimeout(function () {

                    $('#res_message').hide();
                    window.location.href="{{route('client.index')}}"
                    $('#msg_div').hide();
                    $('#send_forms_data').html('Ուղարկված');
                }, 4000);
            }
                });
            }
        })
    }

</script>

</body>
</html>