routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([ 'as' => 'client.', 'namespace' => 'Client'], function () {
    Route::get('/', 'SiteClentsController@index')->name('index');
    Route::get('/about', 'SiteClentsController@about')->name('about');
    Route::get('/reviews', 'SiteClentsController@reviews')->name('reviews');
    Route::get('/blog', 'SiteClentsController@blog')->name('blog');
    Route::get('/contact', 'SiteClentsController@contact')->name('contact');
    Route::get('new/start', 'SiteClentsController@newstart')->name('new_start');


    Route::resource('registers', 'RegisterLessonController');
    Route::get('lessonRegister', 'RegisterLessonController@store')->name('lessonRegister');
    Route::get('callUp', 'RegisterLessonController@CallUpCenter')->name('CallUpCenter');
    Route::get('SendMSG', 'ContactUsController@Send')->name('sendMSG');


    Route::get('/lesson', 'LessonController@lessons')->name('lesson_danisoft');
    Route::get('/price_list', 'LessonController@price')->name('price_list');
    Route::get('/lesson/{data}', 'LessonController@lessonMore')->name('lessonMore');
    Route::get('/lesson-register/{data?}', 'LessonController@lessonRegister')->name('lessonRegister');
    Route::get('gift-card', 'LessonController@GiftCard')->name('gif_card');
});

Auth::routes();

Route::redirect('/home', '/admin');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/notes', 'HomeController@index')->name('home');
    Route::resource('LessonTimeList', 'School\LessonTimeFolderController');
    Route::post('LessonFolderUpdate', 'School\LessonTimeFolderController@updateStudent')->name('LessonFolderUpdate');
    Route::resource('StudentNewMath', 'School\StudentCreatedNewMath');
    Route::get('StudentNewMath/refresh/Student/{id}', 'School\StudentCreatedNewMath@create')->name('StudentNewMath.new.math');
    Route::get('Student/back/Student/{id}', 'School\StudentCreatedNewMath@showThisStudent')->name('StudentNewMath.showThisStudent');
    Route::resource('StudentList', 'School\StudentCreatedNewMath');
    Route::resource('StudentOfDaniSoft', 'School\StudentController');
    Route::post('LessonTimeList/createNew', 'School\LessonTimeFolderController@addLesson')->name('LessonTimeList.addLesson');
    Route::resource('notes', 'Notes\NotesController');
    Route::post('notes/update/type', 'Notes\NotesController@update')->name('notes.update.type');
    Route::get('notes/fav/type/', 'Notes\NotesController@fav')->name('notes.fav.type');

    //regiser lesson
     Route::resource('registerLesson', 'School\Reg\RegisterLessonController');
     Route::post('registerLessonDelete/{id}', 'School\Reg\RegisterLessonController@delete');
     Route::post('lesson/favorite/type/{id}', 'School\Reg\RegisterLessonController@favorite');
     Route::post('lesson/student/{id}', 'School\Reg\RegisterLessonController@student');
     Route::post('lesson/status/{id}', 'School\Reg\RegisterLessonController@status');
     Route::get('lesson/info/{id}', 'School\Reg\RegisterLessonController@info')->name('lessonReg.info');
     Route::post('lesson/info_store', 'School\Reg\RegisterLessonController@info_store')->name('lessonRegComments.info');


    //endregister

    //CallUp lesson
    Route::resource('CallUp', 'CallUp\CallUpController');
    Route::post('CallUpDelete/{id}', 'CallUp\CallUpController@delete');
    Route::post('CallUp/favorite/type/{id}', 'CallUp\CallUpController@favorite');
    Route::post('CallUp/status/{id}', 'CallUp\CallUpController@status');
    //endCallUp
    //
  //regiser lesson
    Route::resource('contact', 'Contact\ContactUsController');
    Route::post('contactDelete/{id}', 'CallUp\CallUpController@delete');
    Route::post('contact/favorite/type/{id}', 'CallUp\CallUpController@favorite');
    Route::post('contact/status/{id}', 'CallUp\CallUpController@status');
    //endregister



    Route::delete('permissions/destroy', 'User\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'User\PermissionsController');
    Route::delete('roles/destroy', 'User\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'User\RolesController');
    Route::delete('users/destroy', 'User\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'User\UsersController');
});

resources/views/admin/School/LessonTimeList/include/AddPrice.blade.php
<div class="dropdown-menu"
     aria-labelledby="{{$students->StudentPrice->status ?? ' '}}-{{$students->StudentPrice->id ?? ' '}}">

    <a href=""
       class="dropdown-item primary">{{$students->StudentPrice->price_full ?? ' '}}
        դրամ</a>
    <a href=""
       class="dropdown-item">{{$students->StudentPrice->day!=null ? $students->StudentPrice->day.' '. 'օր':''}}</a>
    <a href="" class="dropdown-item">
        {{$students->StudentPrice->start_date}}
        <br> {{$students->StudentPrice->end_date}}</a>
    @if($students->StudentPrice->status=='inactive')
        <form
            action="{{route('admin.LessonTimeList.update',$students->id)}}"
            method="post"
            id="priceUppdate{{$students->StudentPrice->id}}">
            @csrf
            @method('put')
            <input type="number" id="price"
                   placeholder="Գումար" name="price">
            <br>
            <br>
            <label for="whatdate"><abbr
                    title=" Վճարելէ ամբողջությամբ">Վճար</abbr></label>
            <input type="checkbox" id="whatdate" name="priceall"
                   value="ok">
            <br>
            <br>
            <a class="dropdown-item primary"
               onclick="document.getElementById('priceUppdate'+{{$students->StudentPrice->id}}).submit()"
            >
                <svg xmlns="http://www.w3.org/2000/svg"
                     width="24" height="24" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor"
                     stroke-width="2" stroke-linecap="round"
                     stroke-linejoin="round"
                     class="feather feather-check">
                    <polyline
                        points="20 6 9 17 4 12"></polyline>
                </svg>

                Վճարված</a>
        </form>
    @else
        <a class="dropdown-item primary"
           href="{{route('admin.StudentNewMath.new.math',$students->id)}}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24" height="24" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor"
                 stroke-width="2" stroke-linecap="round"
                 stroke-linejoin="round"
                 class="feather feather-check">
                <polyline
                    points="20 6 9 17 4 12"></polyline>
            </svg>

            Ստեղծել նոր ամիս</a>
    @endif
</div>

resources/views/admin/School/LessonTimeList/include/NewMonth.blade.php
<a class="dropdown-toggle warning" href="#" role="button"
   id="{{$students->id}}-{{$students->age}}"
   data-toggle="dropdown"
   aria-haspopup="true" aria-expanded="true">
    <svg xmlns="http://www.w3.org/2000/svg" width="24"
         height="24"
         viewBox="0 0 24 24" fill="none"
         stroke="currentColor"
         stroke-width="2" stroke-linecap="round"
         stroke-linejoin="round"
         class="feather feather-alert-octagon">
        <polygon
            points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
        <line x1="12" y1="8" x2="12" y2="12"></line>
        <line x1="12" y1="16" x2="12" y2="16"></line>
    </svg>
</a>
<div class="dropdown-menu"
     aria-labelledby="{{$students->id?? ' '}}-{{$students->age ?? ' '}}">

    <a href=""
       class="dropdown-item primary">0
        դրամ</a>

        <form
            action="{{route('admin.LessonTimeList.update',$students->id)}}"
            method="post"
            id="priceUppdates{{$students->id}}">
            @csrf
            @method('put')
            <input type="number" id="price"
                   placeholder="Գումար" name="price">
            <br>
            <br>
            <label for="whatdate"><abbr
                    title=" Վճարելէ ամբողջությամբ">Վճար</abbr></label>
            <input type="checkbox" id="whatdate" name="priceall"
                   value="ok">
            <br>
            <br>
            <a class="dropdown-item primary"
               onclick="document.getElementById('priceUppdates'+{{$students->id}}).submit()"
            >
                <svg xmlns="http://www.w3.org/2000/svg"
                     width="24" height="24" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor"
                     stroke-width="2" stroke-linecap="round"
                     stroke-linejoin="round"
                     class="feather feather-check">
                    <polyline
                        points="20 6 9 17 4 12"></polyline>
                </svg>

                Վճարված</a>
        </form>

</div>

resources/views/admin/School/LessonTimeList/include/active.blade.php
<a class="dropdown-toggle warning" href="#" role="button"
   id="dropdownMenuLink-{{$students->StudentPrice->status}}-{{$students->StudentPrice->id}}"
   data-toggle="dropdown"
   aria-haspopup="true" aria-expanded="true">
    <svg xmlns="http://www.w3.org/2000/svg" width="24"
         height="24" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="2"
         stroke-linecap="round" stroke-linejoin="round"
         class="feather feather-check">
        <polyline points="20 6 9 17 4 12"></polyline>
    </svg>
</a>

resources/views/admin/School/LessonTimeList/include/inactive.blade.php
<a class="dropdown-toggle warning" href="#" role="button"
   id="{{$students->StudentPrice->status}}-{{$students->StudentPrice->id}}"
   data-toggle="dropdown"
   aria-haspopup="true" aria-expanded="true">
    <svg xmlns="http://www.w3.org/2000/svg" width="24"
         height="24"
         viewBox="0 0 24 24" fill="none"
         stroke="currentColor"
         stroke-width="2" stroke-linecap="round"
         stroke-linejoin="round"
         class="feather feather-alert-octagon">
        <polygon
            points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
        <line x1="12" y1="8" x2="12" y2="12"></line>
        <line x1="12" y1="16" x2="12" y2="16"></line>
    </svg>
</a>

resources/views/admin/School/LessonTimeList/include/new.blade.php
<?php